### ISSUE TITLE
Application channel discovery

### ISSUE THREAD

**Issue by pgn-vole** [finos/FDC3#220] opened 2020-06-30 15:33 UTC
### Question Area
[ ] App Directory
[X] API
[ ] Context Data
[ ] Intents
[ ] Use Cases
[ ] Other

### Question

App specific transient channels can be created using the concept of application channels (ref: https://fdc3.finos.org/docs/next/api/spec#app-channels). It is not specified however how does the Application Chanel ID is provided to potential consumers of that channel.

The use case here is about sharing contexts between a parent application and multiple child applications. Those child applications may all be consuming the same context type but they all would be provided a different context value by the parent application thanks to private application channels.
The idea to put this flow in place is to create ad-hoc individual channels for each child application. However once the child application is started either via `open` or `raiseIntent` it is not clear how to provide the channel id that those sub application should connect to.

Would you have any pointer to handle such use case?

**Comment by rikoe** [comment] 2020-07-06 17:49
@pgn-vole channels and intents are two separate use cases.

For intents, you are leveraging a well-known capability (e.g. "StartChat", "ViewChart") and raising the intent to invoke such a capability without knowing which target application will meet it. An application may be launched on demand to perform the action. I like to think of intents as "active" interoperability operations, e.g. triggered by a button or menu item.

For channels, you are sharing data on a well-known channel. Both parties can connect to the channel id/name and then exchange data. This is more of a "passive" interoperability action, e.g. one app my say "I am currently viewing this", and other apps may chose to listen and do something in response.

We support "system" channels, which are defined by the desktop agent, and known and shared by everyone. You can query what the available system channels are.

We also support "app" channels (which I like to call "private" channels), where the channel name both apps connect to are pre-agreed, or shared in a different manner. It falls out of the scope of FDC3 how these channel names are shared, this is by design.

**Comment by rikoe** [comment] 2020-07-21 10:10
@pgn-vole is the above clear? Can we close this issue?

**Comment by pgn-vole** [comment] 2020-07-28 14:00
@rikoe thanks for the detailed answer. 
My question was regarding some specific aspects of the usage of application channel that would enable parent/child communication. As you mentioned this is outside of the scope of FDC3. However would you have any insight into achieve so?

My thinking was to either rely on a specific context type which would contain an application channel id or alternatively use proprietary app API to pass down the ad-hoc channel id.

```jsx
// Parent app setup a channel
const privateChannel = await fdc3.getOrCreateChannel('private-channel-1')

// Option1:
await raiseIntent('startChart', { type:'customChannel', channelId: 'private-channel-1' })
// Option2:
const { data } = await raiseIntent('startChart')
data.setChannelId('private-channel-1')

// Parent app broadcast to child via app channel
privateChannel.broadcast({ 
 type:'timeseries',
 data:[ ... ]
})
```

**Comment by rikoe** [comment] 2021-04-15 16:50
Closing due to inactivity.

**Closed by rikoe** 2021-04-15 16:50 UTC
