### ISSUE TITLE
Question: adding BrowserTypes to root export

### ISSUE THREAD

**Issue by Roaders** [finos/FDC3#1338] opened 2024-09-04 08:55 UTC
### Question Area
 - [ ] App Directory
 - [x] API
 - [ ] Context Data
 - [ ] Intents
 - [ ] Use Cases
 - [ ] Other

### Question

We've just moved over to the Beta release published under `@kite9` and I noticed that I am still having to import messages from a deep path as `BrowserTypes` is not included in the root export: 

```
import { RaiseIntentForContextRequest } from '@kite9/fdc3/dist/api/BrowserTypes';
```

What is the plan for including these in the root export? There are several naming collisions - do we have a plan for dealing with them?

**Comment by robmoffat** [comment] 2024-09-04 15:38
Adding to #1297

**Comment by kriswest** [comment] 2024-09-04 16:28
I've done the export in 065c0d78ba9ff011eb9c4616a8695890b446bbe8 as BrowserTypes (so the namespace should prevent conflicts) and made an adjustment to fix an existing name conflict with ContextTypes (which was not namespaced like this - although BridgingTypes was, so there is precedent). 

If this works for you @Roaders, then @robmoffat can just merge this in and tick it off his list for now.

**Comment by robmoffat** [comment] 2024-09-05 08:04
Tagging @Lecss

This is great, thanks for tackling that @kriswest.  One quick question - normally I wouldn't check in browserTypes as it is generated from other first-hand code (i.e. your schemas).  What's the argument here for checking it in too?  Or could we simply include the generated version in our npm package?

Interested to hear what @Roaders and @Lecss think on this too.

**Comment by kriswest** [comment] 2024-09-05 08:52
We've always checked in the generated source file for ContextTypes and BridgingTypes, and do so on a pre-commit hook, as this allows us to review and track what is actually changing in the generated code. Were a quicktype update and tweak to the quicktype commands to alter the generated code we'd be able to see that, alongside changes caused by schema updates. Due to schema composition, changes in one schema can affect multiple of the generated source files and multiple elements within each file and due to that complexity, it can be hard for a contributor to know what will be affected by a change they implement in the schema files. Finally, its easy to inadvertently break the schema files through a syntax error or syntactically correct change that results in an unvalidatable schema. This is only revealed by running the code generation scripts (although we could do with further emphasizing the errors when they occur).

Hence, I see only benefits and no downsides to checking in the generated code.

**Comment by kriswest** [comment] 2024-09-05 09:11
A `getAgent()` export would be the next one to add @robmoffat. I know the implementation team this end are keen to start working with it/testing against it ASAP.

**Comment by kriswest** [comment] 2024-09-05 09:39
That reminds me, there is a _/src/GetAgent.ts_ file with the type for the function and args:

```ts
export type getAgent = ( 
  params?: GetAgentParams,  
) => Promise<DesktopAgent>; 
```
But it should probably not be exported as `getAgent` - rather the implementation should be exported as `getAgent` in index.ts. I've gone ahead and renamed the type `GetAgentType` to avoid a conflict or confusion: f4f6009a5bfee84502dfcf7aa1a5343c0636f675

**Comment by Roaders** [comment] 2024-09-05 10:53
> Tagging @Lecss
> 
> This is great, thanks for tackling that @kriswest. One quick question - normally I wouldn't check in browserTypes as it is generated from other first-hand code (i.e. your schemas). What's the argument here for checking it in too? Or could we simply include the generated version in our npm package?
> 
> Interested to hear what @Roaders and @Lecss think on this too.

In this case I think checking it in would be useful so that it's visible in GitHub and people can look at it there. Generally I do not like checking in generated stuff but I think this would be an exception

**Comment by robmoffat** [comment] 2024-09-05 13:19
> A getAgent() export would be the next one to add @robmoffat. I know the implementation team this end are keen to start working with it/testing against it ASAP.

You can use this.  Add the following deps to package.json:

```
   "@kite9/client": "2.2.0-beta.6",
    "@kite9/da-server": "2.2.0-beta.6",
    "@kite9/fdc3": "2.2.0-beta.6",
```

And then just import:

```
import { getAgent } from '@kite9/client'
```

We'll move back to the @finos namespace once the vote goes through, as discussed in a meeting earlier this week

**Comment by kriswest** [comment] 2024-09-11 09:04
@robmoffat did you merge the BrowserTypes export in index.ts and republish? I.e. can we close this as completed? At https://unpkg.com/browse/@kite9/fdc3@2.2.0-beta.6/dist/fdc3.cjs.development.js I see ContextTypes and BridgingTypes, but not yet BrowserTypes so I would assume not.

**Comment by robmoffat** [comment] 2024-09-11 09:15
yes, I've done this in fdc3-for-web-impl.  I'd really like to take you through it as I'm not 100% confident with all these name collisions and picking the right ones

**Comment by robmoffat** [comment] 2024-09-11 09:16
I haven't republished yet

**Comment by kriswest** [comment] 2024-09-11 09:23
I'm around shortly, and can connect with you to take a look @robmoffat

**Closed** 2024-09-18 13:00 UTC
Labels: FDC3 for Web Browsers
