### ISSUE TITLE
App Directory main endpoint and other examples don't match the JSON schema at `interop.intents.raises`

### ISSUE THREAD

**Issue by BalassaMarton** [finos/FDC3#1085] opened 2023-10-04 14:17 UTC
### Area of Issue
[x] App Directory
[ ] API
[ ] Context Data
[ ] Intents
[ ] Desktop Agent Bridging
[ ] Use Cases
[ ] Other

### Issue Description: 
According to the spec, `raises` should map intent names to list of context types:
https://github.com/finos/FDC3/blob/master/src/app-directory/specification/appd.schema.json#L816-L827

But the JSON returned by the AppD main endpoint uses the same schema as for `listensFor` (a map from intent name to intent metadata).
Example: https://github.com/finos-labs/FDC3-App-Directory/blob/main/_apps/adaptabledemo.json#L64-L78

I'm not sure if this is an error in the JSON schema or the examples.

## Additional Context:
FDC3-Sail also has an example JSON file with a non-compliant element: https://github.com/finos/FDC3-Sail/blob/44873c90b99925ac93f9c339407547a1a6652764/directory/local.v2.json#L581-L600

**Comment by kriswest** [comment] 2023-10-04 17:04
@BalassaMarton Thank you for reporting this.
I can confirm that the spec is as intended and that the schema for `interop.intents.raises` and `interop.intents.listensFor` are different (`listensFor` has multiple properties to contain, `raises` does not so is just an array of contexts).
![image](https://github.com/finos/FDC3/assets/1701764/2803a69f-d373-4746-8358-76a0f6fbad5d)

@robmoffat both Sail and the FINOS app directory should be corrected to match the spec. I've raised issues on both and will close this one, see:
- https://github.com/finos-labs/FDC3-App-Directory/issues/30
- https://github.com/finos/FDC3-Sail/issues/145

**Closed by kriswest** 2023-10-04 17:04 UTC
Labels: bug
