### ISSUE TITLE
Documentation links are broken

### ISSUE THREAD

**Issue by thesunlover** [finos/FDC3#938] opened 2023-03-29 08:05 UTC
## Minor Issue
The links or some links under the section https://fdc3.finos.org/docs/api/spec/#desktop-agent-api-standard-compliance target to page 404.

### Area of Issue
[ ] App Directory
[ ] API
[ ] Context Data
[ ] Intents
[ ] Use Cases
[x] Other

### Issue Description: 
STR:

1. Open https://fdc3.finos.org/docs/api/spec/ 
2. go to or scroll to the section Desktop Agent API Standard Compliance and see the list of methods of the [Desktop Agent](https://fdc3.finos.org/docs/api/spec/ref/DesktopAgent)

### Additional Context:
![image](https://user-images.githubusercontent.com/6734600/228466680-9d98dbf4-337b-4f96-8e66-78cdce81dee0.png)
example: https://fdc3.finos.org/docs/api/spec/ref/DesktopAgent#raiseintentforcontext

**Comment by kriswest** [comment] 2023-03-30 11:15
Actually there's something decidedly odd going on with these links @robmoffat. I thought they were correct in next and wrong in 2.0, but it turns out that sometimes they are rendering as:
- https://fdc3.finos.org/docs/api/ref/DesktopAgent#addcontextlistener (works)
![image](https://user-images.githubusercontent.com/1701764/228818473-d5663694-2fac-4521-adb3-05de41ea7bf8.png)

and sometimes as:
- https://fdc3.finos.org/docs/api/spec/ref/DesktopAgent#addcontextlistener (broken)
![image](https://user-images.githubusercontent.com/1701764/228818396-9d1be159-d794-4152-87cb-ab2367ce1bf6.png)

and appears to vary based on whether you've navigated internally in the site (tends to work) or gone direct to the URL direct/refreshed the page (tends to faiL). It does not appear entirely stable.

**Comment by kriswest** [comment] 2023-03-30 11:22
Some more info, if you've navigated around you'll end up on:
https://fdc3.finos.org/docs/api/spec#desktop-agent-api-standard-compliance

If you refresh the page that turns into:
https://fdc3.finos.org/docs/api/spec/#desktop-agent-api-standard-compliance

Resulting in link resolution for relative links being different/broken. 

The issue is not confined to this page, I can replicate it on any of the Standard sections, which all have to use relative links (to support versioning). E.g. links from the intent overview to specific intent pages: https://fdc3.finos.org/docs/intents/spec, or cross links between the different spec parts in all versions of FDC3 (e.g. https://fdc3.finos.org/docs/1.2/context/overview/ link to intents spec).

Hence, its important that we fix this. Hopefully its just a config setting in docusaurus...

**Comment by robmoffat** [comment] 2023-03-30 11:50
The markdown link is definitely wrong in https://github.com/finos/FDC3/blob/master/website/versioned_docs/version-2.0/api/spec.md

It says:

```
- [`DesktopAgent`](ref/DesktopAgent)
```

Should be:

```
- [`DesktopAgent`](../ref/DesktopAgent)
```

What I don't understand is why docusaurus doesn't point this out.  I spent ages fixing all manner of broken links reported by docusaurus during the upgrade, so I can't see why it wouldn't find this one.

**Comment by kriswest** [comment] 2023-03-30 14:09
I'd be pretty surprised if it's NOT the netlify setting causing the issue - as it would explain why docusaurus doesn't report issues. That said, a docusaurus setting that adds the trailing slash would probably result in it modifying the links generated.

I am certain the links are correctly described in the markdown as markdown editors follow them correctly and we've not had trouble before.

**Comment by robmoffat** [comment] 2023-03-30 14:45
Locally works fine for me - can you confirm?

**Comment by kriswest** [comment] 2023-03-30 14:51
Confirmed here too. If you reload the page there is no redirect to a URL with a trailing slash, hence all links are correct.

Hence, can you try disabling Netlify's pretty URLs setting please @robmoffat (as its adding the trailing /) (as I think it better we stick to the old URLs and avoid the unnecessary 301 redirect). If we get no joy with that we can then look at docusaurus' `trailingSlash` setting to emulate the same behavior and adjust link generation for internal nav.

**Comment by robmoffat** [comment] 2023-03-31 09:28
ok, I've updated the settings as per https://stackoverflow.com/questions/75442550/404-error-after-adding-trailingslash-false-in-a-docusaurus-website

We should be able to test this in a preview build now I think

**Comment by robmoffat** [comment] 2023-03-31 09:45
I just pushed a change to this PR: https://github.com/finos/FDC3/pull/925
Preview is here: https://deploy-preview-925--fdc3.netlify.app/docs/api/spec
`DesktopAgent` link looks good to me now.

Can someone verify? And then we can merge that PR and we're fixed.

**Comment by kriswest** [comment] 2023-03-31 12:22
@robmoffat I can confirm that its no longer adding a trailing / when the page is direct loaded or refreshed. If you manually add the trailing slash to the URL (or use a link from elsewhere where someone has done so) it will load the page, but the links will still break - this is a much lesser issue (than the current state where the hosting is actively messing with the URLs and causing the issue).

It may be possible to solve that remaining issue by setting `trailingSlash: false` in the docusaurus config (as it will force removal of the slash). Testing that out now...

**Comment by robmoffat** [comment] 2023-04-04 08:29
Can you approve this: https://github.com/finos/FDC3/pull/925

then we can merge it and close this issue

**Comment by kriswest** [comment] 2023-04-21 17:37
This should now be as resolved as we can manage! No combination of options for docusaurus can fix every permutation (because I couldn't convince it to generate links that assume a trailing slash is added AND not break some of the things in the toolbox folder) but you should now find that:
- Internal links in the site deliver you to https://fdc3.finos.org/docs/api/spec  (no trailing slash)
- On that page, links should be correct, e.g.: at https://fdc3.finos.org/docs/api/spec#desktop-agent-api-standard-compliance the relative links generated are:  https://fdc3.finos.org/docs/api/ref/DesktopAgent#addcontextlistener

However, if you use a link with a trailing slash (as found in the issue definition above), e.g. https://fdc3.finos.org/docs/api/spec/, the (relative) links will be incorrectly resolved, e.g. https://fdc3.finos.org/docs/api/spec/ref/DesktopAgent#addcontextlistener.

**Closed by kriswest** 2023-04-21 17:37 UTC
Labels: bug
