### ISSUE TITLE
Question: When calling agent.addIntentListener() where does the appId come from for that registered intent handler?

### ISSUE THREAD

**Issue by Roaders** [finos/FDC3#1242] opened 2024-07-02 15:18 UTC
### Question Area
 - [ ] App Directory
 - [x] API
 - [ ] Context Data
 - [ ] Intents
 - [ ] Use Cases
 - [ ] Other

### Question

If I call  

```ts
fdc3.addIntentListener('StartChat', myHandler);
```
and I then want to target that handler from another app:

```ts
fdc3.raiseIntent("StartChat", context, 'whatGoesInHere?');
```

where does the appId that the handler is registered against come from? Does an agent have an associated `appId`? If it does then that answers my question but raises others.  

Thinking of this from a web point of view where we have to set window.fdc3 to be our agent, this would mean that one window would only be able to have one appId - this is probably desirable in most circumstances but in some cases might not be optimal.

The other question this raises is what happens if my webapp is running in a container and window.fdc3 is injected from that container. In this case if I call `fdc3.addIntentListener('StartChat', myHandler)` it would be registered against the appId that the container agent is associated with and not my appId that my window is running against.  

I realise that the recommended approach for registering intents is with an app directory. This is not really about registering intents but how an agent instance is associated with apps.

**Comment by kriswest** [comment] 2024-07-02 15:53
>  ``` fdc3.raiseIntent("StartChat", context, 'whatGoesInHere?'); ```
> where does the appId that the handler is registered against come from? Does an agent have an associated appId? If it does then that answers my question but raises others.

First-off, to answer the question embedded in the example code, an appIdentifier should be passed, see: https://fdc3.finos.org/docs/api/ref/Types#appidentifier. That's an object with at least an `appId` property, perhaps also an `instanceId` if its a running app, and a `desktopAgent` if you are working with Desktop Agent Bridging and its on a different DA. Do not use the deprecated `raiseIntent` signature that allows you to pass a string as thats actually a non-unique app name rather than an appId.

However, you don't have to supply an appId, you can let the Desktop Agent and user work it out. If there's only one option most DAs will pick that (auto-resolution), while if there are multiple options (which can include launching a new instance or picking an existing instance of the same app) most DAs implement some form of intent resolver UI allowing the user to pick. Some form of resolution process MUST be provided by a DA, but it can be 'any suitable methodology'.

Next the DA should know the appId for every application. Generally, they will be getting details of apps from an appD or other suitable configuraiton, which will provide the relevant ID. You can gain programmatic access to the available appIds and instanceIds for resolving an intent via [`fdc3.findIntent`](https://fdc3.finos.org/docs/api/ref/DesktopAgent#findintent).

Finally (and for the avoidance of doubt) Desktop Agents do not themselves have appIds, but they are expected to know the `appIds` (and `instanceIds`) of each of the apps they manage.

> Thinking of this from a web point of view where we have to set window.fdc3 to be our agent, this would mean that one window would only be able to have one appId - this is probably desirable in most circumstances but in some cases might not be optimal.

This is currently the case. We've discussed in the 'FDC3 for Web Browsers' discussion group a use case we've ended up calling a 'Micro-Frontend Container', which is single window/DOM hosting multiple applications, which communicate with each other (and potentially apps in other windows) via FDC3. The current proposal for handling that is to create an additional API call to retrieve additional FDC3 API references, each with their own identity - this is necessary as the app instance identity is implied by the API reference you are using. That use case has a full proposal (that builds on/reuses the techniques defined in the FDC3 for the Web proposal) but hasn't received as much interest. If you are keen on that use case, it might be worth raising an issue for it to be supported and I'll redouble efforts to include it in the proposed changes.

However, cases where theres a single window but multiple DOMs (i.e. embedded ifrmaes for additional apps in the window) is dealt with by the main FDC3 for Web Browsers proposal. They will try to contact a 'parent' DA in the parent frame (`window.parent`) or its opener (`window.parent.opener`) and establish communication with it in the same way as a child web app in a new window talking to its opener (`window.opener`).

> The other question this raises is what happens if my webapp is running in a container and window.fdc3 is injected from that container. In this case if I call fdc3.addIntentListener('StartChat', myHandler) it would be registered against the appId that the container agent is associated with and not my appId that my window is running against.

No, when a container injects a copy of the FDC3 API at `window.fdc3`, it must ensure that it is associated with the `appId` and `instanceId` of the application instance. All intent routing, originatingApp identities on broadcasts etc. is dependent on that.

> I realise that the recommended approach for registering intents is with an app directory. This is not really about registering intents but how an agent instance is associated with apps.

To clarify, the appDirectory tells us which apps can be started to resolve an intent and what contexts they support. Once started apps register a listener via a copy of the FDC3 API which should already know their identity (both appId and instanceId) which is why they don't need to state it when registering (which would be a bad design and invite spoofing).

I hope that helps clarify things and answers your questions! If not let me know!

**Comment by Roaders** [comment] 2024-07-03 07:17
Once again many thanks for your detailed answer. I am afraid that I am still a little unclear on some aspects.
I probably didn't word my question very well. I wasn't asking about how it works when you raise an intent with no appId (I understand that mechanisms to resolve an ambiguous intent). I am still unclear however what happens when you call `fdc3.addIntentListener('StartChat', myHandler);`

My current understanding is that an app directory would specify that `AppA` can handle the intent `StartChat`. When an intent is raised and `AppA` is selected I assume that the message is routed to the DA that manages that app.

You state:

> Finally (and for the avoidance of doubt) Desktop Agents do not themselves have appIds, but they are expected to know the appIds (and instanceIds) of each of the apps they manage.

Which obviously means that one DA can manage multiple apps. (as a side question I assume that an appId can only be managed by one agent? or could there by multiple agent instances that manage one appId?)

If I have a DA that manages `AppA` and `AppB` and the App Directory states that both AppA and AppB can handle the `StartChat` intent what happens? Do intents for both `AppA` and `AppB` get handled by the same `IntentHandler`?

**Comment by kriswest** [comment] 2024-07-03 16:01
HI @Roaders, yes conceptually a Desktop Agent is intended to manage multiple applications and route messages between them. A Desktop Agent managing a single app has little purpose in terms of interoperability. Hence, I would probably view your Desktop Agent as a distributed entity (one DA, but with parts running in several different locations). This matters once you start to talk about multiple Desktop Agents talking to each other, which is what the [Desktop Agent Bridging Part of the FDC3 Standard](https://fdc3.finos.org/docs/agent-bridging/spec) is for - its also where a DA managing a single app has more purpose! and the introduction to that part of the Standard may help some with your question...

> Which obviously means that one DA can manage multiple apps. (as a side question I assume that an appId can only be managed by one agent? or could there by multiple agent instances that manage one appId?)

A particular **instance** of an app can only be managed by one application. Technically, there is nothing stopping there being instances of the same app and appId in multiple Desktop Agents.  Take a look at the definition of the `AppIdentifier`:

```ts
interface AppIdentifier {
  /** The unique application identifier located within a specific application
   *  directory instance. An example of an appId might be 'app@sub.root'.
   */
  readonly appId: string;
  
  /** An optional instance identifier, indicating that this object represents a
   *  specific instance of the application described.
   */
  readonly instanceId?: string;

  /** The Desktop Agent that the app is available on. Used in Desktop Agent 
   *  Bridging to identify the Desktop Agent to target.
   *  @experimental
   **/
  readonly desktopAgent?: string;
}
```

`appId` comes from the appDirectory (or your DA's own config if not using an appD), a unique `instanceId` is assigned by the Desktop Agent when it starts the app. When working with bridging, the bridge assigns a name to each Desktop Agent connected to it and will ensure it is applied to any appIdentifiers passing through and by setting it you can target apps across the bridge.

> If I have a DA that manages AppA and AppB and the App Directory states that both AppA and AppB can handle the StartChat intent what happens? Do intents for both AppA and AppB get handled by the same IntentHandler?

Not quite no. Let's say you start 2 instances each of two apps (4 total), as each starts they get their own copy of the FDC3 API injected, with API copy knowing that instance's `appId` and `instanceId`, then each app registers an intent handler function in its own scope for their intents through their own copy of the FDC3 API (`fdc3.addIntentListener('StartChat', myHandler);`. Hence, 4 separate handlers are registered, each associated with a unique _combination_ of `appId` and `instanceId`. Then when an intent is raised it can target any of those 4 handlers (by `appId` and `instanceId` in the `app?: AppIdentifier` argument to `raiseIntent`, or because the user selected one of them in an intent resolver).

It's up to the Desktop Agent API implementation to make sure it knows the `appId` and `instanceId` for each app talking to it, implicitly. Thats not as easily possible with FDC3 on the Web (as the user can go to the app directly if they know the URL and browser sandboxing gets in the way), so the proposal to support that includes additional identity steps where the app provides the URL to its appDirectory record and any instanceId it was provided previously and the Desktop Agent does some validation of that before allowing it to interop with others.

**Comment by Roaders** [comment] 2024-07-04 07:51
I'm sorry if I am being slow but I am still struggling with this a bit. I think that I struggle to understand the difference (which you have explained...) between a desktop agent and an instance of the API...

>  Let's say you start 2 instances each of two apps (4 total), as each starts they get their own copy of the FDC3 API injected

so here there would 4 copies of the `FDC3 API`. They would be different parts of the same Desktop Agent. So each instance of an app has an associated copy of the API that knows the `appId` and the `instanceId` of the app. That all makes sense to me and answers my question about calling `fdc3.addIntentListener`. Where I get a bit lost is how this then works with `window.fdc3`. Are we assuming that all these apps are in different windows? I suppose we probably are. If they are not in separate windows (which they will be in my use case) then we would need to implement the proposal for the sub agents.

So to summarise my understanding. I am building a web app that would have a container (running in a normal browser window) that would have multiple iframes and windows running under under it.
- The whole container, iframes and child windows would run under conceptually one Desktop agent located at `window.fdc3` in the container window
- Each window and iframe running under it would have it's own copy of the DA API which would have an `appId` (non unique) and an `instanceId` (unique)
- The different API copies would communicate with each other over the proposed comms protocol that would use postMessage and Channel API
- There is a 1:1 mapping between API copy and app (currently)
- There is a 1:1 mapping between a browser window and an app (currently)

Is that about right? Thanks for your patience.

**Comment by Roaders** [comment] 2024-07-04 08:39
Brilliant, thanks very much for clarifying all of that for me.

**Comment by kriswest** [comment] 2024-07-04 09:53
Closing as the question is answered (feel free to reopen if more occur). 

@Roaders if you plan to have multiple apps in one window **without** iframes (iframe case is covered in the main proposal - although it doesn't deal directly with containers supporting it I suppose), then it might be worth opening an issue for supporting the ability to retrieve additional copies of the FDC3 API with alternative identities. This was somethign that was discussed at some of the FDC3 for the Web meetings, and has a proposal in that doc, but not an actual issue.

The proposal was to add this function to the API:

```ts
/**	 
 * @param {string} params Required parameters object, which must include  
 * at least a fully qualified appId or appD URL for the application to 
 * indicate the app's identity. 
 * @param {string} params.appId The fully qualified appId 
 * (in the form appid@<appd origin> for the application 
 * @param {URL} params.appDUrl The URL to the appD record providing the  
 * app's identity, used as an alternative to a fully qualified appId. 
 *  
 * @return A promise that resolves to a DesktopAgent implementation or  
 * rejects if the app identity could not be validated. 
 */ 
type getSubAgent = ( 
  params: GetSubAgentParams,  
): Promise<DesktopAgent>  

type GetSubAgentParams = { 
  appId?: string, 
  appDUrl?: URL
} 
```

(i.e. get the FDC3 API at the window level and then have the individual apps in the page request their own API copies, each with their own identity.)

Raising the issue is worthwhile if you need this as there was some talk of separating this out of the main proposal as its less often needed (most attendees needed the main proposal only one or two this addition - and none have yet raised the relevant issue to formally request it).

**Closed** 2024-07-04 09:53 UTC
